#!/usr/bin/env bash

#installing engine X web server
apt-get update
apt-get install -y nginx

/usr/sbin/nginx

echo "Holberton School for the win!" | tee /var/www/html/index.html

if pgrep -x "nginx" > /dev/null
then
    echo "Nginx is running."
else
    echo "Nginx failed to start."
fi