#!/usr/bin/env bash
#installing engine X web server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart

if ps ax | grep -v grep | grep nginx > /dev/null
then
    echo "Nginx is running."
else
    echo "Nginx failed to start."
fi